language: node_js
node_js:
  - "6"
script: npm run coverage && npm run coveralls && npm run eslint && npm install -g browserify && git config --global user.email "travis@tekgenesis.com" && git config --global user.name "Travis" && npm run deploy
