language: node_js
node_js:
  - "6"
script: npm run coverage && npm run coveralls && npm run eslint && npm install -g browserify && git config --global remote.origin.url https://glodieu:$GITHUB_API_KEY@mulesoft.github.io/oas-raml-converter && npm run deploy
