language: node_js
node_js:
  - "6"
script: npm run coverage && npm run coveralls && npm run eslint

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    npm install -g browserify && cd site && npm install && mkdir -p public/build && npm run build
    git push -f -q https://glodieu:$GITHUB_API_KEY@github.com/mulesoft/oas-raml-converter gh-pages &2>/dev/null
  fi
